#Milestone-1
MxoDevops/My-portfolio-microverse pull request #1
Opened 2022-05-25 13:47 UTC by MxoDevops

#Added  a logo and nav bar
#Added background image
#Added heading and paragraph

2022-05-25 14:54 UTC, ishimwezachee requested changes
Hi @MxoDevops  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️

- [OPTIONAL ] Its a good practice to use a descriptive branch name for your pull request.  Next time you can name your branch based on the feature that you've implemented. 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-05-25 14:54 UTC, ishimwezachee commented on MIT.md
>  Permission is hereby granted, free of charge, to any person obtaining a copy of this [APP TYPE] and associated documentation files, to deal in the [APP TYPE] without restriction, including without li
- [ ]  Try to replace your MIT.md file data with your information.  for example, `[APP TYPE]` should be changed to something like [Mobile Portofolio]. This will make your project more professional.

2022-05-25 14:54 UTC, ishimwezachee commented on index.html
> +        <div><i class="fa fa-bars fa-3x"></i></div>
- [ ]  Its a good practice to wrap this part with `<nav>` tag, This improve your website semantics.  For more information check [hrere](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav)

2022-05-25 16:34 UTC, Kossi-stack requested changes
## Hi @MxoDevops ,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-25 16:34 UTC, Kossi-stack commented on index.html
> +          <a class="logo">My Logo</a>
- [ ] Kindly wrap your Logo in a link (tag), Professional websites have a logo as a link, 
Note: your code should like this
![Capturelogo](https://user-images.githubusercontent.com/81444338/170311899-9f2812c3-88c4-493a-8f4c-8e23522568de.PNG)

2022-05-25 16:34 UTC, Kossi-stack commented on README.md
>  - GitHub: MxoDevops
- [ ] kindly fellow this sample
![Capturemedia](https://user-images.githubusercontent.com/81444338/170314581-4a4e51c6-e0d9-4aca-bd12-648d7e729d0e.PNG)

2022-05-26 05:10 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @MxoDevops 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 05:10 UTC, tresorsawasawa commented on README.md
>  ### Run tests
- [ **OPTIONAL** ] I think it would be better :100: if you remove now these sections as they don't have any content. You can add them once you have something to write there. This will make your documentation looks more professional.

2022-05-26 05:10 UTC, tresorsawasawa commented on README.md
- [ **OPTIONAL** ] I suggest you remove one of these sections as they are duplicates to make your documentation cleaner. And if possible add some commands on how to Install **webint** and **styleint** you can add this one: `npm install`
 Once someone cloned the project, it will install all the project dependencies.

2022-05-26 05:23 UTC, merged